// Etch-a-Sketch

// Get a random color to set as the background color for each square as you enter it
function getRandomColor() {
    const randomColor = Math.random() * 256;
    return randomColor;
    
}

// Change the background of each square to be a random color generated by the getRandomColor() function
function randomizeSquareColor(e) {
    e.target.style.cssText = `background: rgb(${getRandomColor()}, ${getRandomColor()}, ${getRandomColor()})`;
}

// Make the squares get darker after each pass by the user's mouse
// After 10 passes, the shade of the square will be completely black
function increaseShadeOfSquare(e) {
    const startColor = 225;
    const darker = 25;
    const currentSquare = Number(e.target.getAttribute("id") - 1);
    let shadeOfSquare = startColor-(darker*(gridSquares[currentSquare]));
    if (shadeOfSquare >= 0) {
        gridSquares[currentSquare]++;
        e.target.style.cssText = `background: rgb(${shadeOfSquare}, ${shadeOfSquare}, ${shadeOfSquare})`;
    }
}

// Set up a “hover” effect so that the grid divs change color when the mouse passes over them, 
// It will leave a (pixelated) trail through the grid like a pen would
function shadeHover() {
    const squares = document.querySelectorAll(".square");
    squares.forEach((square) => {
        square.addEventListener("mouseenter", increaseShadeOfSquare);
    });
}

function colorHover() {
    const randButton = document.querySelector("#random-color");
    randButton.addEventListener("click", () => {
        const squares = document.querySelectorAll(".square");
        squares.forEach((square) => {
            square.addEventListener("mouseenter", randomizeSquareColor);
        });
    });
}

function reset() {
    const reset = document.querySelector("#reset");
    reset.addEventListener("click", () => {
        const squares = document.querySelectorAll(".square");
        squares.forEach((square) => {
            square.style.cssText = "background: rgb(255,255,255)";
        });
    });
}

// Create a webpage with a grid of square divs
// Create the divs using JavaScript if the user enters a valid grid number
function makeNewGrid() {
    let gridSize = +prompt("How many squares per side would you like for your grid?\nEnter an integer between 1 and 100");
    while (!Number.isInteger(gridSize) || (gridSize < 1 && gridSize !== 0)|| gridSize > 100) {
        gridSize = +prompt("Please enter a valid integer between 1 and 100");
    }

    div.textContent = "";
    div.style.cssText = "display: block";

    let count = 1;
    for (let i = 0; i < gridSize; i++) {
        const row = document.createElement("div");
        row.classList.add("row");
        div.appendChild(row);
        for (let j = 0; j < gridSize; j++) {
            const square = document.createElement("div");
            square.classList.add("square");
            square.setAttribute("id", count);
            row.appendChild(square);
            count++;
        }
        row.style.cssText = `grid-template-columns: repeat(${gridSize},1fr)`;
    }
    for (let i = 0; i < (div.childElementCount*div.childElementCount); i++) {
        gridSquares[i] = 0;
    } 

    shadeHover();
    colorHover();
    reset();
}

// Prompt the user to enter the number of squares on each side of the grid layout
// The user will receive the prompt after pressing a button
const div = document.querySelector("div.info-container");
const gridSquares = [];
const gridButton = document.querySelector("#new-grid");
gridButton.addEventListener("click", makeNewGrid);